### ISSUE TITLE
Not able to connect from other containers in docker-compose

### ISSUE THREAD

**Issue by krystianolech** [Azure/azure-event-hubs-emulator-installer#11]
**Describe the bug**
It is not possible to comunicate to emulator form other docker services.
It works fine for emulator started over docker to locally running services, but it does not work on docker network

**To Reproduce**
Minimal reproduction issue:
https://github.com/krystianolech/event-hub-emulator-issue

If we would run this docker-compose (docker-compose up -d) and then run local nodejs script, message are publihed.
However same service within docker is not able to send message and is hanging while trying to send message.
For local connection string is used:
Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;EntityPath=eh1;UseDevelopmentEmulator=true;
while in docker endpoint is changed to name of container with emulator:
sb://eventhubs-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;EntityPath=eh1;UseDevelopmentEmulator=true;

I tried both Endpoint=sb://eventhubs-emulator and Endpoint=sb://emulator.
Setting any name give ENOTFOUND error so its clear that service is connecting to emulator container 

**Docker Version:**
Docker version 26.1.1, build 4cf5afa

**Arguments && Environment variables to start Emulator:**
- ACCEPT_EULA:Y

**Emulator Launch Method:**
 - Direct Docker compose

**Comment by krishankumar95** [comment]
This is related to: https://github.com/Azure/azure-event-hubs-emulator-installer/issues/9 

As a working alternative you can try out the following setup: 
```
name: "eventhubs-emulator-with-containerized-app"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    network_mode: host

  emulator:
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    volumes:
      - "./Config.json:/Eventhubs_Emulator/ConfigFiles/Config.json"
    environment:
      BLOB_SERVER: localhost
      METADATA_SERVER: localhost
      ACCEPT_EULA: "N"
    network_mode: host
    depends_on:
      - azurite

  sample-containerized-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    depends_on:
      - emulator
```

Few things to note:

a) EULA Flag

b) Connection string used :
```
"Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;EntityPath=eh1;UseDevelopmentEmulator=true;"
```
c) Sample application should wait for few seconds to allow Emulator to bootup and accept requests
