### ISSUE TITLE
How to connect local function `func start`

### ISSUE THREAD

**Issue by ranma2913** [Azure/azure-event-hubs-emulator-installer#16]
I'm developing a Javascript v4 function. It's working fine in cloud, but on local I'm not able to connect to my docker-compose started Event Hub Emulator.

I have Questions:

- How do I produce events from my cli into the`eventhubs-emulator`
- How do I setup the local.settings.json file?

I'm using the connection string provided in the documentation `Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;` but get a connection refused: 
```logs
Functions:

        MyEventHubTrigger: eventHubTrigger

For detailed output, run func with --verbose flag.
[2024-06-06T16:52:49.253Z] Host lock lease acquired by instance ID '000000000000000000000000B4975DB8'.
[2024-06-06T16:52:56.304Z] EventProcessorHost error (Action='Retrieving list of partition identifiers from a Consumer Client.', HostName='52656bb6-5546-409b-a571-14550d79f670', PartitionId='').
[2024-06-06T16:52:56.304Z] System.Private.CoreLib: Connection refused.
[2024-06-06T16:52:56.313Z] The listener for function 'Functions.MyEventHubTrigger' was unable to start.
[2024-06-06T16:52:56.313Z] The listener for function 'Functions.MyEventHubTrigger' was unable to start. System.Private.CoreLib: One or more errors occurred. (Connection refused). System.Private.CoreLib: Connection refused.
```

**Comment by ranma2913** [comment]
https://www.reddit.com/r/AZURE/comments/1d9no6y/azureeventhubsemulator_local_connection_refused/

**Comment by Saglodha** [comment]
@ranma2913 - You don't need to change anything for SharedAccessKey=SAS_KEY_VALUE. Other questions in your issue seems related to #15, can you review it to get more details on local.settings.json? 

Additionally, I have similar questions on your setup- Where are the local function and emulator running and how does the networking topology look like?

**Comment by ranma2913** [comment]
I'm starting the azure emulator with docker-compose like so:
![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/4295880/1377351f-2c9d-4645-9b96-6bbc27479545)

docker-compose.yaml
```yaml
name: microsoft-azure-emulators
services:
  emulator:
    container_name: "eventhubs-emulator"
    image: "mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest"
    volumes:
      - "./eventhubs_emulator_config.json:/Eventhubs_Emulator/ConfigFiles/config.json"
    ports:
      - "5672:5672"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      CONFIG_PATH: '/Eventhubs_Emulator/ConfigFiles/config.json'
      ACCEPT_EULA: 'Y'
    depends_on:
      - azurite
    networks:
      eh-emulator:
        aliases:
          - "eventhubs-emulator"
  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      eh-emulator:
        aliases:
          - "azurite"
networks:
  eh-emulator:
```

eventhubs_emulator_config.json
```json
{
  "UserConfig" : {
    "NamespaceConfig" : [
      {
        "Type" : "EventHub",
        "Name" : "emulatorNs1",
        "Entities" : [
          {
            "Name" : "call-summary",
            "PartitionCount" : "2",
            "ConsumerGroups" : [
              {
                "Name" : "acet"
              }
            ]
          }
        ]
      }
    ],
    "LoggingConfig" : {
      "Type" : "Console,File"
    }
  }
}
```
And then I start the local function:
```shell
cd CallSummaryFunctionApp/
func start --verbose
```
![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/4295880/91a34b75-87e1-464c-bc0d-f9e46e235d4d)
