### ISSUE TITLE
Mapped Config.json Volume is Ignored

### ISSUE THREAD

**Issue by cawoodm** [Azure/azure-event-hubs-emulator-installer#45]
We have mapped our own `Config.json` (with pre-defined topics) into the Docker Container but it has zero effect - there is no error, but there is also no effect and some default Config.json is used.

* *Expected Behaviour* Config should be read, topics should exist on startup
* *Actual Behaviour* Config is ignored, no topics (except `eh1`) exist

Sadly the container image contains no shell so there is no way to get inside the container (e.g. with `docker exec -it ... /bin/bash`) and see whats happening.

### Config.json
```json
{
  "UserConfig": {
    "NamespaceConfig": [
      {
        "Type": "EventHub",
        "Name": "emulatorNs1",
        "Entities": [
          {
            "Name": "data.foo.1",
            "PartitionCount": 1,
            "ConsumerGroups": [
              {
                "Name": "$Default"
              }
            ]
          },
          {
            "Name": "data.bar.1",
            "PartitionCount": 1,
            "ConsumerGroups": [
              {
                "Name": "$Default"
              }
            ]
          }
        ]
      }
    ],
    "LoggingConfig": {
      "Type": "Console,File"
    }
  }
}
```

### Docker Compose
```yaml
name: microsoft-azure-eventhubs
services:
  emulator:
    container_name: "eventhubs-emulator"
    image: "mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest"
    volumes:
      - "${CONFIG_PATH}:/Eventhubs_Emulator/Config/Config.json"
    ports:
      - "5672:5672"
      - "9092:9092"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - azurite
    networks:
      eh-emulator:
        aliases:
          - "eventhubs-emulator"
  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      eh-emulator:
        aliases:
          - "azurite"

networks:
  eh-emulator:

```

### start.sh
```bash
export ACCEPT_EULA=Y
export CONFIG_PATH=/mnt/c/projects/azure-event-hubs-emulator-installer/EventHub-Emulator/Config/Config.json
docker-compose -f docker-compose-marc.yml down
docker-compose -f docker-compose-marc.yml up
```

### docker inspect eventhubs-emulator
```
...
"HostConfig": {
            "Binds": [
                "/mnt/c/projects/azure-event-hubs-emulator-installer/EventHub-Emulator/Config/Config.json:/Eventhubs_Emulator/Config/Config.json:rw"
            ],
...
```

### Log Shows Config.json is ignored
```
eventhubs-emulator  |       Emulator is launching with config : {"LoggingConfig":{"Type":"File"},"NamespaceConfig":[{"Type":"EventHub","Name":"emulatorns1","Entities":[{"Name":"eh1","PartitionCount":2,"ConsumerGroups":[{"Name":"cg1"},{"Name":"$default"}]}]}]}
```

### Browse with Kafka Magic
![Image](https://github.com/user-attachments/assets/79a7cde7-b0fd-4eb9-a3ac-678ceb237030)
