### ISSUE TITLE
I have troubles persisting the checkpoints between container restarts

### ISSUE THREAD

**Issue by oskaremil** [Azure/azure-event-hubs-emulator-installer#58]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to update my Event Hub processor client configuration with a new blob storage container for checkpoints after restarting the Azurite/Event Hub Emulator containers.

I use _docker compose_ to orchestrate my local developer environment.

`docker compose down` works as expected. Since the _azurite_ container is removed, the checkpoint container is also removed and my event processor client will start from scratch on next `docker compose up`

`docker compose stop` does not work as expected. The container is simply stopped, no containers or volumes are removed. When I restart the container, an offset exception has happened. It materializes as error messages like this:

An exception occurred while processing events for partition '*' by processor instance with identifier '***' for Event Hub: *** and Consumer Group: ***.  Error Message: 'The supplied sequence number '71181' is invalid. The last sequence number in the system is '1048' 

TrackingId:046df2cc-aa31-42ac-b5aa-6ed9d869c0ac_G0, 
SystemTracker:emulatorns1:eventHub:***~32766, 
Timestamp:2025-05-06T07:40:34 Reference:5948714d-2c40-4626-b554-6a28cbded0f5, 
TrackingId:e0d1878a-6034-444e-8ee8-7d8fafc4217f_G0, 
SystemTracker:emulatorns1:eventHub:***~32766|***, 
Timestamp:2025-05-06T07:40:34 TrackingId:8a9381836a7748cfa0a8a8f9fc11eed5_G0, 
SystemTracker:gateway1, Timestamp:2025-05-06T07:40:34

**Describe the solution you'd like**
Any advice on how to persist checkpoints between sessions

**Describe alternatives you've considered**

Mounting azurite with its own data volume: 

```
  azurite:
    container_name: "azurite"
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    restart: unless-stopped
    entrypoint: ["azurite", "--blobHost", "0.0.0.0", "--blobPort", "10000","-l", "data"]
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - azurite_data:/opt/azurite/data

volumes:
  azurite_data:
```

Azurite seems to be fine with this, but now event hub emulator refuses to start and I have a looping error message like: 

fail: a.D.aDr[0]
2025-05-06T08:39:19.535244062Z       Emulator Start up probe Unsuccessful. MetadataStore Health status: Unhealthy BlobStore Health status: Healthy
2025-05-06T08:39:19.535251108Z fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[103]
2025-05-06T08:39:19.535252457Z       Health check Emulator Health Check with status Unhealthy completed after 3011.7335ms with message 'Emulator Start up probe Unsuccessful. MetadataStore Health status: Unhealthy BlobStore Health status: Healthy'

**Additional context**

These are not problems that i experience in the Azure environment, if I point my event hub processor client to an Azure Event Hub and use an Azure Storage Account for checkpoints. This is limited to local development with Azurite and/or the Event Hub emulator docker images.

From the error message, my event processor client has consumed and stored offset 71181, but when azurite or event hub emulator is restarted, the latest available offset is 1048
